name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reference-implementation

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

    # - name: Check formatting
    # run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run tests
        run: cargo test --workspace --all-targets



